name: Run Lives Tests

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  selected-tests:
    runs-on: ubuntu-latest
    environment: Production
    strategy:
      matrix:
        python-version: [3.11]
        include:
          - test-name: ALCF
            test-file: tests/alcf_server_test.py
          - test-name: NERSC
            test-file: tests/nersc_server_test.py
          - test-name: Diaspora
            test-file: tests/diaspora_server_test.py

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run ${{ matrix.test-name }} tests
        env:
          DIASPORA_CLIENT_ID: ${{ env.DIASPORA_CLIENT_ID }}
          DIASPORA_CLIENT_SECRET: ${{ env.DIASPORA_CLIENT_SECRET }}
        run: tox -e py311 -- ${{ matrix.test-file }}
