name: Run Lives Tests

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  selected-tests:
    runs-on: ubuntu-latest
    environment: AWS
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run only ALCF & NERSC tests
        env:
          DIASPORA_CLIENT_ID: ${{ secrets.DIASPORA_CLIENT_ID }}
          DIASPORA_CLIENT_SECRET: ${{ secrets.DIASPORA_CLIENT_SECRET }}
        run: tox -e py311 -- tests/alcf_server_test.py tests/nersc_server_test.py tests/diaspora_server_test.py
